use super::super::{ApiMethodSpec, HttpMethod};
use super::{
    TAG_AUTH, TAG_COMMENT, TAG_DANMAKU, TAG_EMOJI, TAG_LIVE, TAG_MUSIC, TAG_SEARCH, TAG_USER,
    TAG_WORK,
};

pub(super) const DOUYIN_METHODS: [ApiMethodSpec; 19] = [
    ApiMethodSpec {
        method_key: "parseWork",
        chinese_name: "聚合解析",
        fetcher_name: "parseWork",
        route: "/work/{aweme_id}",
        http_method: HttpMethod::Get,
        description: "Parse a work URL or identifier and infer the content type.",
        tags: TAG_WORK,
    },
    ApiMethodSpec {
        method_key: "videoWork",
        chinese_name: "视频作品数据",
        fetcher_name: "fetchVideoWork",
        route: "/work/{aweme_id}/video",
        http_method: HttpMethod::Get,
        description: "Fetch a Douyin video work.",
        tags: TAG_WORK,
    },
    ApiMethodSpec {
        method_key: "imageAlbumWork",
        chinese_name: "图集作品数据",
        fetcher_name: "fetchImageAlbumWork",
        route: "/work/{aweme_id}/image-album",
        http_method: HttpMethod::Get,
        description: "Fetch a Douyin image album work.",
        tags: TAG_WORK,
    },
    ApiMethodSpec {
        method_key: "slidesWork",
        chinese_name: "合辑作品数据",
        fetcher_name: "fetchSlidesWork",
        route: "/work/{aweme_id}/slides",
        http_method: HttpMethod::Get,
        description: "Fetch a Douyin slides work.",
        tags: TAG_WORK,
    },
    ApiMethodSpec {
        method_key: "textWork",
        chinese_name: "文字作品数据",
        fetcher_name: "fetchTextWork",
        route: "/work/{aweme_id}/text",
        http_method: HttpMethod::Get,
        description: "Fetch a Douyin text work.",
        tags: TAG_WORK,
    },
    ApiMethodSpec {
        method_key: "comments",
        chinese_name: "评论数据",
        fetcher_name: "fetchWorkComments",
        route: "/comments/{aweme_id}",
        http_method: HttpMethod::Get,
        description: "Fetch comments for a Douyin work.",
        tags: TAG_COMMENT,
    },
    ApiMethodSpec {
        method_key: "commentReplies",
        chinese_name: "指定评论回复数据",
        fetcher_name: "fetchCommentReplies",
        route: "/comment-replies/{aweme_id}/{comment_id}",
        http_method: HttpMethod::Get,
        description: "Fetch replies for a Douyin comment.",
        tags: TAG_COMMENT,
    },
    ApiMethodSpec {
        method_key: "userProfile",
        chinese_name: "用户主页数据",
        fetcher_name: "fetchUserProfile",
        route: "/user/{sec_uid}",
        http_method: HttpMethod::Get,
        description: "Fetch a Douyin user profile.",
        tags: TAG_USER,
    },
    ApiMethodSpec {
        method_key: "userVideoList",
        chinese_name: "用户主页视频列表数据",
        fetcher_name: "fetchUserVideoList",
        route: "/user/{sec_uid}/videos",
        http_method: HttpMethod::Get,
        description: "Fetch published videos for a Douyin user.",
        tags: TAG_USER,
    },
    ApiMethodSpec {
        method_key: "userFavoriteList",
        chinese_name: "用户主页喜欢列表数据",
        fetcher_name: "fetchUserFavoriteList",
        route: "/user/{sec_uid}/favorites",
        http_method: HttpMethod::Get,
        description: "Fetch favorite works for a Douyin user.",
        tags: TAG_USER,
    },
    ApiMethodSpec {
        method_key: "userRecommendList",
        chinese_name: "用户主页推荐列表数据",
        fetcher_name: "fetchUserRecommendList",
        route: "/user/{sec_uid}/recommends",
        http_method: HttpMethod::Get,
        description: "Fetch recommendation feeds for a Douyin user.",
        tags: TAG_USER,
    },
    ApiMethodSpec {
        method_key: "search",
        chinese_name: "搜索数据",
        fetcher_name: "searchContent",
        route: "/search",
        http_method: HttpMethod::Get,
        description: "Search Douyin content.",
        tags: TAG_SEARCH,
    },
    ApiMethodSpec {
        method_key: "suggestWords",
        chinese_name: "热点词数据",
        fetcher_name: "fetchSuggestWords",
        route: "/search/suggest",
        http_method: HttpMethod::Get,
        description: "Fetch Douyin search suggestion keywords.",
        tags: TAG_SEARCH,
    },
    ApiMethodSpec {
        method_key: "musicInfo",
        chinese_name: "音乐数据",
        fetcher_name: "fetchMusicInfo",
        route: "/music/{music_id}",
        http_method: HttpMethod::Get,
        description: "Fetch Douyin music metadata.",
        tags: TAG_MUSIC,
    },
    ApiMethodSpec {
        method_key: "liveRoomInfo",
        chinese_name: "直播间信息数据",
        fetcher_name: "fetchLiveRoomInfo",
        route: "/live/{room_id}",
        http_method: HttpMethod::Get,
        description: "Fetch Douyin live room information.",
        tags: TAG_LIVE,
    },
    ApiMethodSpec {
        method_key: "loginQrcode",
        chinese_name: "申请二维码数据",
        fetcher_name: "requestLoginQrcode",
        route: "/auth/qrcode",
        http_method: HttpMethod::Get,
        description: "Request a Douyin login QR code.",
        tags: TAG_AUTH,
    },
    ApiMethodSpec {
        method_key: "emojiList",
        chinese_name: "Emoji数据",
        fetcher_name: "fetchEmojiList",
        route: "/emoji",
        http_method: HttpMethod::Get,
        description: "Fetch the Douyin emoji catalog.",
        tags: TAG_EMOJI,
    },
    ApiMethodSpec {
        method_key: "dynamicEmojiList",
        chinese_name: "动态表情数据",
        fetcher_name: "fetchDynamicEmojiList",
        route: "/emoji/dynamic",
        http_method: HttpMethod::Get,
        description: "Fetch Douyin animated emoji data.",
        tags: TAG_EMOJI,
    },
    ApiMethodSpec {
        method_key: "danmakuList",
        chinese_name: "弹幕数据",
        fetcher_name: "fetchDanmakuList",
        route: "/danmaku/{aweme_id}",
        http_method: HttpMethod::Get,
        description: "Fetch Douyin danmaku data.",
        tags: TAG_DANMAKU,
    },
];
