use super::super::{ApiMethodSpec, HttpMethod};
use super::{TAG_SEARCH, TAG_SPACE, TAG_USER};

const TAG_TWEET: &[&str] = &["tweet"];

pub(super) const TWITTER_METHODS: [ApiMethodSpec; 17] = [
    ApiMethodSpec {
        method_key: "searchTweets",
        chinese_name: "搜索推文",
        fetcher_name: "searchTweets",
        route: "/search/tweets",
        http_method: HttpMethod::Get,
        description: "Search Twitter/X tweets by raw query.",
        tags: TAG_SEARCH,
    },
    ApiMethodSpec {
        method_key: "userProfile",
        chinese_name: "用户资料",
        fetcher_name: "fetchUserProfile",
        route: "/user/{screen_name}",
        http_method: HttpMethod::Get,
        description: "Fetch a Twitter/X user profile by screen name.",
        tags: TAG_USER,
    },
    ApiMethodSpec {
        method_key: "userTimeline",
        chinese_name: "用户时间线",
        fetcher_name: "fetchUserTimeline",
        route: "/user/{screen_name}/timeline",
        http_method: HttpMethod::Get,
        description: "Fetch a Twitter/X user timeline by screen name.",
        tags: TAG_USER,
    },
    ApiMethodSpec {
        method_key: "userReplies",
        chinese_name: "用户回复",
        fetcher_name: "fetchUserReplies",
        route: "/user/{screen_name}/replies",
        http_method: HttpMethod::Get,
        description: "Fetch a Twitter/X user's replies by screen name.",
        tags: TAG_USER,
    },
    ApiMethodSpec {
        method_key: "userMedia",
        chinese_name: "用户媒体",
        fetcher_name: "fetchUserMedia",
        route: "/user/{screen_name}/media",
        http_method: HttpMethod::Get,
        description: "Fetch a Twitter/X user's media timeline by screen name.",
        tags: TAG_USER,
    },
    ApiMethodSpec {
        method_key: "userFollowers",
        chinese_name: "用户粉丝",
        fetcher_name: "fetchUserFollowers",
        route: "/user/{screen_name}/followers",
        http_method: HttpMethod::Get,
        description: "Fetch a Twitter/X user's followers by screen name.",
        tags: TAG_USER,
    },
    ApiMethodSpec {
        method_key: "userFollowing",
        chinese_name: "用户关注",
        fetcher_name: "fetchUserFollowing",
        route: "/user/{screen_name}/following",
        http_method: HttpMethod::Get,
        description: "Fetch a Twitter/X user's following list by screen name.",
        tags: TAG_USER,
    },
    ApiMethodSpec {
        method_key: "userLikes",
        chinese_name: "用户点赞",
        fetcher_name: "fetchUserLikes",
        route: "/user/likes",
        http_method: HttpMethod::Get,
        description: "Fetch liked tweets for the authenticated Twitter/X account.",
        tags: TAG_USER,
    },
    ApiMethodSpec {
        method_key: "userBookmarks",
        chinese_name: "用户书签",
        fetcher_name: "fetchUserBookmarks",
        route: "/user/bookmarks",
        http_method: HttpMethod::Get,
        description: "Fetch the authenticated Twitter/X user's bookmarks.",
        tags: TAG_USER,
    },
    ApiMethodSpec {
        method_key: "userFollowed",
        chinese_name: "关注时间线",
        fetcher_name: "fetchUserFollowed",
        route: "/user/followed",
        http_method: HttpMethod::Get,
        description: "Fetch the authenticated Twitter/X followed feed.",
        tags: TAG_USER,
    },
    ApiMethodSpec {
        method_key: "userRecommended",
        chinese_name: "推荐时间线",
        fetcher_name: "fetchUserRecommended",
        route: "/user/recommended",
        http_method: HttpMethod::Get,
        description: "Fetch the authenticated Twitter/X recommended feed.",
        tags: TAG_USER,
    },
    ApiMethodSpec {
        method_key: "searchUsers",
        chinese_name: "搜索用户",
        fetcher_name: "searchUsers",
        route: "/search/users",
        http_method: HttpMethod::Get,
        description: "Search Twitter/X users by keyword.",
        tags: TAG_SEARCH,
    },
    ApiMethodSpec {
        method_key: "tweetDetail",
        chinese_name: "推文详情",
        fetcher_name: "fetchTweetDetail",
        route: "/tweet/{tweet_id}",
        http_method: HttpMethod::Get,
        description: "Fetch a Twitter/X tweet by tweet id.",
        tags: TAG_TWEET,
    },
    ApiMethodSpec {
        method_key: "tweetReplies",
        chinese_name: "推文回复",
        fetcher_name: "fetchTweetReplies",
        route: "/tweet/{tweet_id}/replies",
        http_method: HttpMethod::Get,
        description: "Fetch replies for a Twitter/X tweet by tweet id.",
        tags: TAG_TWEET,
    },
    ApiMethodSpec {
        method_key: "tweetLikers",
        chinese_name: "推文点赞用户",
        fetcher_name: "fetchTweetLikers",
        route: "/tweet/{tweet_id}/likers",
        http_method: HttpMethod::Get,
        description: "Fetch users who liked a Twitter/X tweet by tweet id.",
        tags: TAG_TWEET,
    },
    ApiMethodSpec {
        method_key: "tweetRetweeters",
        chinese_name: "推文转推用户",
        fetcher_name: "fetchTweetRetweeters",
        route: "/tweet/{tweet_id}/retweeters",
        http_method: HttpMethod::Get,
        description: "Fetch users who retweeted a Twitter/X tweet by tweet id.",
        tags: TAG_TWEET,
    },
    ApiMethodSpec {
        method_key: "spaceDetail",
        chinese_name: "Space详情",
        fetcher_name: "fetchSpaceDetail",
        route: "/space/{space_id}",
        http_method: HttpMethod::Get,
        description: "Fetch a Twitter/X Space by space id.",
        tags: TAG_SPACE,
    },
];
