use serde::{Deserialize, Serialize};

use super::super::utils::parse_cookie_entries;

/// HTTP methods supported by the Xiaohongshu signer.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum XiaohongshuMethod {
    /// Sign a `GET` request.
    Get,
    /// Sign a `POST` request.
    Post,
}

/// Ordered cookie container that preserves the original cookie order.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct CookieJar {
    entries: Vec<(String, String)>,
}

impl CookieJar {
    /// Create cookies from ordered key-value pairs.
    pub fn new(entries: Vec<(impl Into<String>, impl Into<String>)>) -> Self {
        Self {
            entries: entries
                .into_iter()
                .map(|(key, value)| (key.into(), value.into()))
                .collect(),
        }
    }

    /// Parse a semicolon-separated cookie string.
    pub fn parse(cookie: &str) -> Self {
        Self {
            entries: parse_cookie_entries(cookie),
        }
    }

    /// Return the first cookie value for a key.
    pub fn get(&self, key: &str) -> Option<&str> {
        self.entries
            .iter()
            .find(|(entry_key, _)| entry_key == key)
            .map(|(_, value)| value.as_str())
    }

    /// Return the ordered cookie entries.
    pub fn entries(&self) -> &[(String, String)] {
        &self.entries
    }
}

/// Structured Xiaohongshu headers generated by the signer.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct XiaohongshuHeaders {
    /// Request `x-s` header.
    pub x_s: String,
    /// Request `x-s-common` header.
    pub x_s_common: String,
    /// Request `x-t` header in milliseconds.
    pub x_t: String,
    /// Request `x-b3-traceid` header.
    pub x_b3_traceid: String,
    /// Request `x-xray-traceid` header.
    pub x_xray_traceid: String,
}

/// Decoded outer `x-s` envelope.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct XiaohongshuXsEnvelope {
    /// SDK version.
    pub x0: String,
    /// App identifier.
    pub x1: String,
    /// Platform identifier.
    pub x2: String,
    /// Inner `x3` payload.
    pub x3: String,
    /// Reserved field.
    pub x4: String,
}

/// Browser-derived signing state required by the rebuilt Xiaohongshu signer.
///
/// The pure-protocol signer no longer needs this runtime state, but the type is
/// kept as a legacy compatibility surface for existing callers.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct XiaohongshuBrowserState {
    /// Platform string exposed by the browser runtime, such as `Windows`.
    pub platform: String,
    /// Browser app identifier used by the web signer.
    pub app_id: String,
    /// Browser app version used by the web signer.
    pub app_version: String,
    /// Signer version embedded into `x-s` and `x-s-common`.
    pub sign_version: String,
    /// DS script timestamp returned by `getdss()`.
    pub dss: String,
    /// Runtime DS marker exposed as `window._dsl`.
    pub dsl: String,
    /// Runtime DS last-load timestamp from `localStorage["dsllt"]`.
    pub dsllt: String,
    /// Runtime load timestamp exposed as `window.loadts`.
    pub loadts: String,
    /// Browser localStorage value `b1`.
    pub b1: String,
    /// Browser localStorage value `b1b1`.
    pub b1b1: String,
    /// Optional mini user-agent replacement used by some realtime paths.
    pub mini_ua: Option<String>,
    /// Stable session-scoped `_dsf()` byte vector captured from the browser.
    pub dsf: Vec<u8>,
    /// Session sign counter mirrored from `sessionStorage["sc"]`.
    pub sign_count: u32,
}

impl Default for XiaohongshuBrowserState {
    fn default() -> Self {
        Self {
            platform: "Windows".to_owned(),
            app_id: "xhs-pc-web".to_owned(),
            app_version: "6.2.1".to_owned(),
            sign_version: "4.3.3".to_owned(),
            dss: String::new(),
            dsl: String::new(),
            dsllt: String::new(),
            loadts: String::new(),
            b1: String::new(),
            b1b1: "1".to_owned(),
            mini_ua: None,
            dsf: Vec::new(),
            sign_count: 0,
        }
    }
}

/// Deterministic Xiaohongshu signing input reconstructed from the pure protocol flow.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct XiaohongshuMnsv2Input {
    /// Pure API path used by the `a3` checksum chain.
    pub sign_path: String,
    /// Full request content string used by the outer MD5 digest.
    pub full_input: String,
    /// MD5 of `sign_path`.
    pub md5_path: String,
    /// MD5 of `full_input`.
    pub md5_full: String,
}

/// Structured payload encoded into `x-s-common`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct XiaohongshuXsCommonPayload {
    /// Platform code derived from the browser platform string.
    pub s0: u32,
    /// Reserved field.
    pub s1: String,
    /// `b1b1` marker.
    pub x0: String,
    /// Signer version.
    pub x1: String,
    /// Platform string.
    pub x2: String,
    /// App identifier.
    pub x3: String,
    /// App version.
    pub x4: String,
    /// `a1` cookie value.
    pub x5: String,
    /// Reserved field.
    pub x6: String,
    /// Reserved field.
    pub x7: String,
    /// `b1` or mini user-agent replacement.
    pub x8: String,
    /// Signed CRC32 variant over `x8`.
    pub x9: i32,
    /// Reserved counter field kept at zero by the pure-protocol signer.
    pub x10: u32,
    /// Sign mode.
    pub x11: String,
}
