use super::{TAG_LIVE, TAG_SEARCH, TAG_SPACE, TAG_USER};
use amagi_core::{ApiOperationSpec, HttpMethod};

const TAG_TWEET: &[&str] = &["tweet"];
const TAG_USER_LIVE: &[&str] = &["user", "live"];
const TAG_LIVE_STREAM: &[&str] = &["live", "stream"];

pub(super) const TWITTER_METHODS: [ApiOperationSpec; 22] = [
    ApiOperationSpec {
        method_key: "searchTweets",
        chinese_name: "搜索推文",
        fetcher_name: "searchTweets",
        route: "/search/tweets",
        http_method: HttpMethod::Get,
        description: "Search Twitter/X tweets by raw query.",
        tags: TAG_SEARCH,
    },
    ApiOperationSpec {
        method_key: "userProfile",
        chinese_name: "用户资料",
        fetcher_name: "fetchUserProfile",
        route: "/user/{screen_name}",
        http_method: HttpMethod::Get,
        description: "Fetch a Twitter/X user profile by screen name.",
        tags: TAG_USER,
    },
    ApiOperationSpec {
        method_key: "userTimeline",
        chinese_name: "用户时间线",
        fetcher_name: "fetchUserTimeline",
        route: "/user/{screen_name}/timeline",
        http_method: HttpMethod::Get,
        description: "Fetch a Twitter/X user timeline by screen name.",
        tags: TAG_USER,
    },
    ApiOperationSpec {
        method_key: "userReplies",
        chinese_name: "用户回复",
        fetcher_name: "fetchUserReplies",
        route: "/user/{screen_name}/replies",
        http_method: HttpMethod::Get,
        description: "Fetch a Twitter/X user's replies by screen name.",
        tags: TAG_USER,
    },
    ApiOperationSpec {
        method_key: "userMedia",
        chinese_name: "用户媒体",
        fetcher_name: "fetchUserMedia",
        route: "/user/{screen_name}/media",
        http_method: HttpMethod::Get,
        description: "Fetch a Twitter/X user's media timeline by screen name.",
        tags: TAG_USER,
    },
    ApiOperationSpec {
        method_key: "userFollowers",
        chinese_name: "用户粉丝",
        fetcher_name: "fetchUserFollowers",
        route: "/user/{screen_name}/followers",
        http_method: HttpMethod::Get,
        description: "Fetch a Twitter/X user's followers by screen name.",
        tags: TAG_USER,
    },
    ApiOperationSpec {
        method_key: "userFollowing",
        chinese_name: "用户关注",
        fetcher_name: "fetchUserFollowing",
        route: "/user/{screen_name}/following",
        http_method: HttpMethod::Get,
        description: "Fetch a Twitter/X user's following list by screen name.",
        tags: TAG_USER,
    },
    ApiOperationSpec {
        method_key: "userLikes",
        chinese_name: "用户点赞",
        fetcher_name: "fetchUserLikes",
        route: "/user/likes",
        http_method: HttpMethod::Get,
        description: "Fetch liked tweets for the authenticated Twitter/X account.",
        tags: TAG_USER,
    },
    ApiOperationSpec {
        method_key: "userBookmarks",
        chinese_name: "用户书签",
        fetcher_name: "fetchUserBookmarks",
        route: "/user/bookmarks",
        http_method: HttpMethod::Get,
        description: "Fetch the authenticated Twitter/X user's bookmarks.",
        tags: TAG_USER,
    },
    ApiOperationSpec {
        method_key: "userFollowed",
        chinese_name: "关注时间线",
        fetcher_name: "fetchUserFollowed",
        route: "/user/followed",
        http_method: HttpMethod::Get,
        description: "Fetch the authenticated Twitter/X followed feed.",
        tags: TAG_USER,
    },
    ApiOperationSpec {
        method_key: "userRecommended",
        chinese_name: "推荐时间线",
        fetcher_name: "fetchUserRecommended",
        route: "/user/recommended",
        http_method: HttpMethod::Get,
        description: "Fetch the authenticated Twitter/X recommended feed.",
        tags: TAG_USER,
    },
    ApiOperationSpec {
        method_key: "liveRoomInfo",
        chinese_name: "直播间信息",
        fetcher_name: "fetchLiveRoomInfo",
        route: "/user/{screen_name}/live-room-info",
        http_method: HttpMethod::Get,
        description: "Fetch Twitter/X live room information by screen name.",
        tags: TAG_USER_LIVE,
    },
    ApiOperationSpec {
        method_key: "liveRoomInfoByUserId",
        chinese_name: "按用户ID获取直播间信息",
        fetcher_name: "fetchLiveRoomInfoByUserId",
        route: "/user-id/{user_id}/live-room-info",
        http_method: HttpMethod::Get,
        description: "Fetch Twitter/X live room information by numeric user id.",
        tags: TAG_LIVE,
    },
    ApiOperationSpec {
        method_key: "liveRoomStream",
        chinese_name: "直播间播放流",
        fetcher_name: "fetchLiveRoomStream",
        route: "/live-room/{broadcast_id}/stream",
        http_method: HttpMethod::Get,
        description: "Resolve a Twitter/X live-room master HLS stream by broadcast id.",
        tags: TAG_LIVE_STREAM,
    },
    ApiOperationSpec {
        method_key: "liveRoomStreamByMediaKey",
        chinese_name: "按媒体Key获取直播间播放流",
        fetcher_name: "fetchLiveRoomStreamByMediaKey",
        route: "/live-media/{media_key}/stream",
        http_method: HttpMethod::Get,
        description: "Resolve a Twitter/X live-room master HLS stream by media key.",
        tags: TAG_LIVE_STREAM,
    },
    ApiOperationSpec {
        method_key: "liveRoomStreamByTweetId",
        chinese_name: "按推文ID获取直播间播放流",
        fetcher_name: "fetchLiveRoomStreamByTweetId",
        route: "/tweet/{tweet_id}/live-room-stream",
        http_method: HttpMethod::Get,
        description: "Resolve a Twitter/X live-room master HLS stream from a tweet broadcast card.",
        tags: TAG_LIVE_STREAM,
    },
    ApiOperationSpec {
        method_key: "searchUsers",
        chinese_name: "搜索用户",
        fetcher_name: "searchUsers",
        route: "/search/users",
        http_method: HttpMethod::Get,
        description: "Search Twitter/X users by keyword.",
        tags: TAG_SEARCH,
    },
    ApiOperationSpec {
        method_key: "tweetDetail",
        chinese_name: "推文详情",
        fetcher_name: "fetchTweetDetail",
        route: "/tweet/{tweet_id}",
        http_method: HttpMethod::Get,
        description: "Fetch a Twitter/X tweet by tweet id.",
        tags: TAG_TWEET,
    },
    ApiOperationSpec {
        method_key: "tweetReplies",
        chinese_name: "推文回复",
        fetcher_name: "fetchTweetReplies",
        route: "/tweet/{tweet_id}/replies",
        http_method: HttpMethod::Get,
        description: "Fetch replies for a Twitter/X tweet by tweet id.",
        tags: TAG_TWEET,
    },
    ApiOperationSpec {
        method_key: "tweetLikers",
        chinese_name: "推文点赞用户",
        fetcher_name: "fetchTweetLikers",
        route: "/tweet/{tweet_id}/likers",
        http_method: HttpMethod::Get,
        description: "Fetch users who liked a Twitter/X tweet by tweet id.",
        tags: TAG_TWEET,
    },
    ApiOperationSpec {
        method_key: "tweetRetweeters",
        chinese_name: "推文转推用户",
        fetcher_name: "fetchTweetRetweeters",
        route: "/tweet/{tweet_id}/retweeters",
        http_method: HttpMethod::Get,
        description: "Fetch users who retweeted a Twitter/X tweet by tweet id.",
        tags: TAG_TWEET,
    },
    ApiOperationSpec {
        method_key: "spaceDetail",
        chinese_name: "Space详情",
        fetcher_name: "fetchSpaceDetail",
        route: "/space/{space_id}",
        http_method: HttpMethod::Get,
        description: "Fetch a Twitter/X Space by space id.",
        tags: TAG_SPACE,
    },
];
